version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trade
    volumes:
      - ./master_db/data:/var/lib/mysql
      - ./master_db/config/:/etc/mysql/conf.d
    ports:
      - "3306:3306"
